language: ruby
rvm:
  - 2.2.3
  - 2.2.2
  - 2.1.5

addons:
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - psql -c 'create database dummy_test;' -U postgres
  - bin/setup

script: bin/test