language: ruby
rvm:
  - 2.2.3
  - 2.2.2
  - 2.1.5

addons:
  postgresql: "9.3"

services:
  - postgresql

gemfile:
  - gemfiles/Gemfile.rails-4.2-stable
  - gemfiles/Gemfile.rails-4.1-stable
  - gemfiles/Gemfile.rails-4.0-stable
  - Gemfile

before_script:
  - psql -c 'create database dummy_test;' -U postgres
  - bin/setup

script: bin/test
